name: "DevSecOps IaC Security Scan"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  iac-security:
    name: "Lint and IaC Scan"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.0

      - name: Terraform Format Check
        run: terraform fmt -check

      - name: Install Trivy
        uses: aquasecurity/setup-trivy@v0.2.2
        with:
          cache: true

      - name: Run Trivy Secret Scan
        run: |
          trivy fs --security-checks secret --exit-code 1 .

      - name: Run Trivy IaC Security Scan
        run: |
          trivy config --severity HIGH,CRITICAL --exit-code 1 .