name: "DevSecOps IaC Security Scan"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  iac-security:
    name: "Lint and IaC Scan (Trivy)"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.0

      - name: Terraform Format Check
        run: terraform fmt -check

      - name: Install Trivy
        uses: aquasecurity/setup-trivy@v0.2.6

      - name: Run Trivy Secret Scan
        run: |
          trivy fs --security-checks secret --exit-code 1 .

      - name: Run Trivy IaC Security Scan
        run: |
          trivy config --severity HIGH,CRITICAL --ignorefile .trivyignore --exit-code 1 .

  checkov-scan:
    name: "Compliance and IaC Scan (Checkov)"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Checkov
        run: pip install checkov

      - name: Run Checkov Scan
        run: |
          checkov -d . --framework terraform --compact \
            --skip-check CKV_AWS_130,CKV_AWS_260,CKV_AWS_126,CKV_AWS_135,CKV_AWS_88,CKV2_AWS_61,CKV2_AWS_12,CKV2_AWS_11,CKV_AWS_18,CKV2_AWS_62,CKV_AWS_144,CKV_AWS_145